### PR TITLE
Model fixes

### PR DESCRIPTION
**Pull request by avanlinden**
- clean up missing tissue valid values
- reduce description length of individualCommonGenotype attribute so it doesn't exceed the 300 character maximum on the dictionary table column

### CODE REVIEW

**Comment by avanlinden** [comment]
@ryaxley The definition for the key `individualCommonGenotype` was super duper long and causing conflicts with the dictionary table -- I shortened it to where it seemed logical, but wanted to let you know. We could potentially go into more detail elsewhere and provide a link to the expanded description in the data model/dictionary if you think it's needed!

**Comment by avanlinden** [comment]
merging to proceed with dictionary table branch

**Comment by ryaxley** [comment]
@avanlinden Thank you. That term is being deprecated given the confusion around the term since the beginning.

**Comment by avanlinden** [comment]
@ryaxley even better!

**Pull request merged**
