### PR TITLE
Update study.csv

### PR DESCRIPTION
**Pull request by ameliakallaher**
added study abbreviation for MARS WISCONSIN study in line 2

### CODE REVIEW

**Review by avanlinden — APPROVED** [review]
Nice! Looks good

**Comment by ameliakallaher** [comment]
@avanlinden Once these changes are approved, do I need to merge the pull request to deploy the branch?

**Comment by avanlinden** [comment]
@ameliakallaher Yeah, we have to merge the PR and then I usually delete the branch after merge to keep things somewhat tidy. I think I absorbed that usual dev practice is to let the person who opened the PR do the merge just in case they had more changes or something they were working on, but that won't always apply to us here so if you're chill with the reviewer merging after approval we can do that too.

**Comment by ameliakallaher** [comment]
@avanlinden I'm good with either workflow - whichever is easier for you; just let me know.

**Comment by avanlinden** [comment]
@ameliakallaher Cool, let's go with "whoever opened it merges it", with the option to communicate an exception as needed! 👍🏻

**Comment by ameliakallaher** [comment]
@avanlinden Ok, and then you said it's best practice to delete the branch once merged?

**Comment by avanlinden** [comment]
@ameliakallaher Yeah, I prefer to delete the branch after I merge changes. If I need to make more changes, I can always make a new branch that has all those changes, since it was merged into main!

**Pull request merged**
