### PR TITLE
Added new term 'lysophospholipids' under module 'metabolomics'

### PR DESCRIPTION
**Pull request by MasterPastures**
Updated AD.model.csv to include new terms 'lysophospholipids' and 'Leiden Oxylipins'

### CODE REVIEW

**Review by avanlinden — DISMISSED** [review]
Looks good!

**Comment by MasterPastures** [comment]
Approved and merging my two commits to add 'lysophospholipids' and 'Leiden Oxipilins,' respectively into the AD data model

**Comment by avanlinden** [comment]
@MasterPastures Sorry to do this, I was looking to see why the automated checks hadn't run and I realized that you edited the `AD.model.csv` directly. Can you edit the module csvs instead? E.g. go to modules -> experimentalData -> assay.csv and edit there. Then the script that rolls up the changes into the full csv and generates the json-ld will run!

**Comment by avanlinden** [comment]
Merged in #60 and #61, closing this.

**Pull request closed without merging**
